"use client";

import { useState } from "react";
import { Check, Copy, Loader2, RefreshCw, Sparkles } from "lucide-react";

import { api } from "@/lib/api";
import { TONE_META, type Lead, type Tone } from "@/lib/types";

export interface FollowupDraft {
  tone: Tone;
  text: string;
  source: string;
}

const TONES: Tone[] = ["friendly", "formal", "short"];

function SourceTag({ source }: { source: string }) {
  const llm = source === "llm";
  return (
    <span
      title={
        llm
          ? "Generated by the configured LLM"
          : "Generated by the built-in offline fallback (no API key configured)"
      }
      className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-medium ring-1 ring-inset ${
        llm
          ? "bg-emerald-50 text-emerald-700 ring-emerald-600/20"
          : "bg-slate-100 text-slate-500 ring-slate-500/20"
      }`}
    >
      {llm ? "LLM" : "offline fallback"}
    </span>
  );
}

export function AiPanel({
  lead,
  draft,
  onDraftChange,
  onSummary,
  onError,
}: {
  lead: Lead;
  draft: FollowupDraft | undefined;
  onDraftChange: (d: FollowupDraft | undefined) => void;
  onSummary: (leadId: number, summary: string) => void;
  onError: (msg: string) => void;
}) {
  const [tab, setTab] = useState<"summary" | "followup">("summary");
  const [summarySource, setSummarySource] = useState<string | null>(null);
  const [loadingSummary, setLoadingSummary] = useState(false);
  const [loadingDraft, setLoadingDraft] = useState(false);
  const [tone, setTone] = useState<Tone>(draft?.tone ?? "friendly");
  const [copied, setCopied] = useState(false);

  const summarize = async () => {
    setLoadingSummary(true);
    try {
      const res = await api.summarize(lead.id);
      setSummarySource(res.source);
      onSummary(lead.id, res.summary);
    } catch (e) {
      onError(e instanceof Error ? e.message : "Failed to summarize");
    } finally {
      setLoadingSummary(false);
    }
  };

  const generateDraft = async () => {
    setLoadingDraft(true);
    try {
      const res = await api.followup(lead.id, tone);
      onDraftChange({ tone, text: res.message, source: res.source });
    } catch (e) {
      onError(e instanceof Error ? e.message : "Failed to draft follow-up");
    } finally {
      setLoadingDraft(false);
    }
  };

  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      onError("Clipboard unavailable — select the text and copy manually");
    }
  };

  return (
    <section
      aria-label="AI tools"
      className="rounded-xl border border-indigo-100 bg-white shadow-sm"
    >
      <header className="flex items-center gap-1 border-b border-slate-100 px-3 pt-2">
        <button
          onClick={() => setTab("summary")}
          className={`-mb-px border-b-2 px-3 py-2 text-sm font-medium transition ${
            tab === "summary"
              ? "border-indigo-600 text-indigo-700"
              : "border-transparent text-slate-500 hover:text-slate-700"
          }`}
        >
          <Sparkles className="mr-1.5 inline h-3.5 w-3.5" />
          Note summary
        </button>
        <button
          onClick={() => setTab("followup")}
          className={`-mb-px border-b-2 px-3 py-2 text-sm font-medium transition ${
            tab === "followup"
              ? "border-indigo-600 text-indigo-700"
              : "border-transparent text-slate-500 hover:text-slate-700"
          }`}
        >
          Follow-up draft
        </button>
      </header>

      <div className="p-3">
        {tab === "summary" ? (
          <div>
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <span className="text-xs font-medium text-slate-500">Interaction summary</span>
                {summarySource && <SourceTag source={summarySource} />}
              </div>
              <button
                onClick={() => void summarize()}
                disabled={loadingSummary}
                className="inline-flex flex-none items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white shadow-sm transition hover:bg-indigo-500 disabled:cursor-wait disabled:opacity-60"
              >
                {loadingSummary ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : lead.ai_summary ? (
                  <RefreshCw className="h-3.5 w-3.5" />
                ) : (
                  <Sparkles className="h-3.5 w-3.5" />
                )}
                {lead.ai_summary ? "Regenerate" : "Summarize notes"}
              </button>
            </div>
            {lead.ai_summary ? (
              <div className="mt-2.5 rounded-lg bg-slate-50 p-3">
                <p className="text-sm leading-relaxed whitespace-pre-wrap text-slate-700">
                  {lead.ai_summary}
                </p>
              </div>
            ) : (
              <p className="mt-2.5 text-sm text-slate-400">
                No summary yet — generate one to get a 3-line recap of this conversation.
              </p>
            )}
          </div>
        ) : (
          <div>
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div className="inline-flex rounded-lg bg-slate-100 p-0.5" role="group" aria-label="Tone">
                {TONES.map((t) => (
                  <button
                    key={t}
                    onClick={() => setTone(t)}
                    className={`rounded-md px-2.5 py-1 text-xs font-medium transition ${
                      tone === t
                        ? "bg-white text-slate-900 shadow-sm"
                        : "text-slate-500 hover:text-slate-700"
                    }`}
                  >
                    {TONE_META[t]}
                  </button>
                ))}
              </div>
              <div className="flex items-center gap-2">
                {draft && <SourceTag source={draft.source} />}
                <button
                  onClick={() => void generateDraft()}
                  disabled={loadingDraft}
                  className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white shadow-sm transition hover:bg-indigo-500 disabled:cursor-wait disabled:opacity-60"
                >
                  {loadingDraft ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : draft ? (
                    <RefreshCw className="h-3.5 w-3.5" />
                  ) : (
                    <Sparkles className="h-3.5 w-3.5" />
                  )}
                  {draft ? "Regenerate" : "Draft message"}
                </button>
              </div>
            </div>
            {draft ? (
              <div className="mt-2.5">
                <textarea
                  value={draft.text}
                  onChange={(e) => onDraftChange({ ...draft, text: e.target.value })}
                  rows={9}
                  className="thin-scroll w-full resize-y rounded-lg border border-slate-200 bg-white p-3 font-mono text-[13px] leading-relaxed text-slate-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 focus:outline-none"
                  aria-label="Follow-up message draft — editable"
                />
                <div className="mt-2 flex items-center justify-between">
                  <p className="text-xs text-slate-400">Editable — tweak it before you send.</p>
                  <button
                    onClick={() => void copy(draft.text)}
                    className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 transition hover:border-slate-300"
                  >
                    {copied ? (
                      <>
                        <Check className="h-3.5 w-3.5 text-emerald-500" /> Copied
                      </>
                    ) : (
                      <>
                        <Copy className="h-3.5 w-3.5" /> Copy
                      </>
                    )}
                  </button>
                </div>
              </div>
            ) : (
              <p className="mt-2.5 text-sm text-slate-400">
                Generate a ready-to-send follow-up email based on this lead&apos;s notes.
              </p>
            )}
          </div>
        )}
      </div>
    </section>
  );
}
