"use client";

import { useState } from "react";

import { api } from "@/lib/api";
import { TONE_META, type Lead, type Tone } from "@/lib/types";

export interface FollowupDraft {
  tone: Tone;
  text: string;
  source: string;
}

const TONES: Tone[] = ["friendly", "formal", "short"];

function SourceNote({ source }: { source: string }) {
  return (
    <span className="text-xs text-zinc-400">
      {source === "llm" ? "generated by Gemini" : "generated offline (no API key)"}
    </span>
  );
}

export function AiPanel({
  lead,
  draft,
  onDraftChange,
  onSummary,
  onError,
}: {
  lead: Lead;
  draft: FollowupDraft | undefined;
  onDraftChange: (d: FollowupDraft | undefined) => void;
  onSummary: (leadId: number, summary: string) => void;
  onError: (msg: string) => void;
}) {
  const [tab, setTab] = useState<"summary" | "followup">("summary");
  const [summarySource, setSummarySource] = useState<string | null>(null);
  const [loadingSummary, setLoadingSummary] = useState(false);
  const [loadingDraft, setLoadingDraft] = useState(false);
  const [tone, setTone] = useState<Tone>(draft?.tone ?? "friendly");
  const [copied, setCopied] = useState(false);

  const summarize = async () => {
    setLoadingSummary(true);
    try {
      const res = await api.summarize(lead.id);
      setSummarySource(res.source);
      onSummary(lead.id, res.summary);
    } catch (e) {
      onError(e instanceof Error ? e.message : "Failed to summarize");
    } finally {
      setLoadingSummary(false);
    }
  };

  const generateDraft = async () => {
    setLoadingDraft(true);
    try {
      const res = await api.followup(lead.id, tone);
      onDraftChange({ tone, text: res.message, source: res.source });
    } catch (e) {
      onError(e instanceof Error ? e.message : "Failed to draft follow-up");
    } finally {
      setLoadingDraft(false);
    }
  };

  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      onError("Clipboard unavailable — select the text and copy manually");
    }
  };

  const primaryBtn =
    "rounded bg-zinc-900 px-2.5 py-1 text-xs font-medium text-white transition hover:bg-zinc-700 disabled:cursor-wait disabled:opacity-60";

  return (
    <section aria-label="AI tools" className="rounded border border-zinc-200 bg-white">
      <header className="flex items-center gap-4 border-b border-zinc-100 px-3 pt-2">
        <button
          onClick={() => setTab("summary")}
          className={`-mb-px border-b-2 px-1 pb-1.5 text-sm transition ${
            tab === "summary"
              ? "border-zinc-900 text-zinc-900"
              : "border-transparent text-zinc-500 hover:text-zinc-700"
          }`}
        >
          Summary
        </button>
        <button
          onClick={() => setTab("followup")}
          className={`-mb-px border-b-2 px-1 pb-1.5 text-sm transition ${
            tab === "followup"
              ? "border-zinc-900 text-zinc-900"
              : "border-transparent text-zinc-500 hover:text-zinc-700"
          }`}
        >
          Follow-up draft
        </button>
      </header>

      <div className="p-3">
        {tab === "summary" ? (
          <div>
            <div className="flex items-center justify-between gap-2">
              <SourceNote source={summarySource ?? (lead.ai_summary ? "cached" : "")} />
              <button
                onClick={() => void summarize()}
                disabled={loadingSummary}
                className={primaryBtn}
              >
                {loadingSummary ? "Summarizing…" : lead.ai_summary ? "Regenerate" : "Summarize notes"}
              </button>
            </div>
            {lead.ai_summary ? (
              <p className="mt-2.5 border-l-2 border-zinc-200 pl-3 text-sm leading-relaxed whitespace-pre-wrap text-zinc-700">
                {lead.ai_summary}
              </p>
            ) : (
              <p className="mt-2.5 text-sm text-zinc-400">
                No summary yet — generate one to get a 3-line recap of this conversation.
              </p>
            )}
          </div>
        ) : (
          <div>
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div className="flex items-center gap-1" role="group" aria-label="Tone">
                {TONES.map((t) => (
                  <button
                    key={t}
                    onClick={() => setTone(t)}
                    className={`rounded px-2 py-0.5 text-xs transition ${
                      tone === t
                        ? "bg-zinc-900 font-medium text-white"
                        : "text-zinc-500 hover:bg-zinc-100 hover:text-zinc-700"
                    }`}
                  >
                    {TONE_META[t]}
                  </button>
                ))}
              </div>
              <div className="flex items-center gap-2">
                {draft && <SourceNote source={draft.source} />}
                <button
                  onClick={() => void generateDraft()}
                  disabled={loadingDraft}
                  className={primaryBtn}
                >
                  {loadingDraft ? "Drafting…" : draft ? "Regenerate" : "Draft message"}
                </button>
              </div>
            </div>
            {draft ? (
              <div className="mt-2.5">
                <textarea
                  value={draft.text}
                  onChange={(e) => onDraftChange({ ...draft, text: e.target.value })}
                  rows={9}
                  className="thin-scroll w-full resize-y rounded border border-zinc-300 bg-white p-2.5 font-mono text-[13px] leading-relaxed text-zinc-700 focus:border-zinc-500 focus:outline-none"
                  aria-label="Follow-up message draft — editable"
                />
                <div className="mt-2 flex items-center justify-between">
                  <p className="text-xs text-zinc-400">Editable — tweak it before you send.</p>
                  <button
                    onClick={() => void copy(draft.text)}
                    className="rounded border border-zinc-300 bg-white px-2.5 py-1 text-xs font-medium text-zinc-700 transition hover:bg-zinc-100"
                  >
                    {copied ? "Copied" : "Copy"}
                  </button>
                </div>
              </div>
            ) : (
              <p className="mt-2.5 text-sm text-zinc-400">
                Generate a ready-to-send follow-up email based on this lead&apos;s notes.
              </p>
            )}
          </div>
        )}
      </div>
    </section>
  );
}
